### ISSUE TITLE
Where are econ1, econ2, econ3 codes

### ISSUE THREAD

**Issue by rgrp** [os-data/boost-paraguay#3]
Only have econ4, econ5

**Comment by danfowler** [comment]
The "Description of Variables" sheet from the original excel file says this: "** ECON1 through ECON3 correspond to the economic classification, which is only available for central and decentralized entities."

**Comment by danfowler** [comment]
More clearly, there are two types of datasets they provide: "spending figures for the central government and the decentralized agencies" and "expenditure data for municipal governments".  We have the latter in this package.  Should I include the rest?

**Comment by rgrp** [comment]
@danfowler can we get a sample for both.

**Comment by danfowler** [comment]
This was done.
